-- Data insert using https://mockaroo.com/
insert into users (user_name, user_email) values ('Diane-marie Farahar', 'dfarahar0@blinklist.com');
insert into users (user_name, user_email) values ('Philly Viney', 'pviney1@barnesandnoble.com');
insert into users (user_name, user_email) values ('Claudette Boecke', 'cboecke2@example.com');
insert into users (user_name, user_email) values ('Sarajane Northway', 'snorthway3@wp.com');
insert into users (user_name, user_email) values ('Cleon Endrici', 'cendrici4@cdbaby.com');
insert into surveys (survey_name) values ('Eare');
insert into surveys (survey_name) values ('Tagopia');
insert into surveys (survey_name) values ('Edgeclub');
INSERT INTO questions (survey_id, question_text) VALUES (1, 'What is your favorite color?');
INSERT INTO questions (survey_id, question_text) VALUES (1, 'How satisfied are you with our service?');
INSERT INTO questions (survey_id, question_text) VALUES (2, 'How often do you use our product?');
INSERT INTO questions (survey_id, question_text) VALUES (1, 'Would you recommend us to a friend?');
INSERT INTO questions (survey_id, question_text) VALUES (3, 'What can we improve about our service?');
INSERT INTO questions (survey_id, question_text) VALUES (1, 'What features do you value most?');
INSERT INTO questions (survey_id, question_text) VALUES (2, 'How did you hear about us?');
INSERT INTO questions (survey_id, question_text) VALUES (3, 'What is your age group?');
insert into responses (user_id, question_id, response_text) values (1, 3, 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id');
insert into responses (user_id, question_id, response_text) values (1, 7, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla');
insert into responses (user_id, question_id, response_text) values (4, 8, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat');
insert into responses (user_id, question_id, response_text) values (2, 3, 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue');
insert into responses (user_id, question_id, response_text) values (5, 7, 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac');
insert into responses (user_id, question_id, response_text) values (3, 3, 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel');
insert into responses (user_id, question_id, response_text) values (4, 7, 'volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna');
insert into responses (user_id, question_id, response_text) values (5, 1, 'erat id mauris vulputate elementum nullam varius nulla facilisi');
insert into responses (user_id, question_id, response_text) values (5, 7, 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede');
insert into responses (user_id, question_id, response_text) values (1, 2, 'turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas');
insert into responses (user_id, question_id, response_text) values (1, 6, 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi');
insert into responses (user_id, question_id, response_text) values (5, 7, 'rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam');
insert into responses (user_id, question_id, response_text) values (3, 7, 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor');
insert into responses (user_id, question_id, response_text) values (1, 2, 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus');
insert into responses (user_id, question_id, response_text) values (4, 8, 'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris');
insert into responses (user_id, question_id, response_text) values (5, 2, 'mauris eget massa tempor convallis nulla neque libero convallis');
insert into responses (user_id, question_id, response_text) values (5, 7, 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes');
insert into responses (user_id, question_id, response_text) values (3, 1, 'dui vel nisl duis ac nibh fusce lacus purus');
insert into responses (user_id, question_id, response_text) values (4, 2, 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna');
insert into responses (user_id, question_id, response_text) values (5, 7, 'nulla nunc purus phasellus in');
insert into responses (user_id, question_id, response_text) values (5, 8, 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac');
insert into responses (user_id, question_id, response_text) values (4, 2, 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at');
insert into responses (user_id, question_id, response_text) values (2, 5, 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa');
insert into responses (user_id, question_id, response_text) values (3, 1, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus');
insert into responses (user_id, question_id, response_text) values (1, 2, 'elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean');
insert into responses (user_id, question_id, response_text) values (2, 7, 'nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis');
insert into responses (user_id, question_id, response_text) values (3, 7, 'posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi');
insert into responses (user_id, question_id, response_text) values (3, 2, 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat');
insert into responses (user_id, question_id, response_text) values (1, 2, 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue');
insert into responses (user_id, question_id, response_text) values (2, 5, 'et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue');
